export const REPLACE_SKILL_LIST = "REPLACE_SKILL_LIST";
export const ADD_TO_SKILL_LIST = "ADD_TO_SKILL_LIST";

export const REPLACE_USER_LIST = "REPLACE_USER_LIST";
export const ADD_TO_USER_LIST = "ADD_TO_USER_LIST";