export const ADD_INTEREST = "ADD_INTEREST";
export const ADD_USER = "ADD_USER";
export const UPDATE_INTEREST = "UPDATE_INTEREST"
export const UPDATE_USER = "UPDATE_USER"
export const INPUT_ALL_INTERESTS = "INPUT_ALL_INTERESTS"