---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: latest

inputs:
  - name: dev
outputs:
  - name: master

run:
  path: dev/ci/scripts/push_to_master.sh