---
resources:
  - name: dev
    type: git
    source:
      uri: https://github.com/demonintherough/talent-id.git
      branch: dev
  - name: master
    type: git
    source:
      uri: https://github.com/demonintherough/talent-id.git
      branch: master
      username: PockyJocky
      password: Y0sh1m0t@

jobs:
  - name: JUnit Tests
    plan:
      - get: dev
        trigger: true
      - task: run the Unit test suite
        file: dev/ci/tasks/Unit_tests.yml
  - name: CodeceptJS UI Tests
    plan:
      - get: dev
        trigger: true
      - task: run the UI test suite
        file: dev/ci/tasks/UI_tests.yml
  - name: Push to Master
    plan:
    - get: dev
      trigger: true
      passed: [JUnit Tests]
    - put: master
      params:
        repository: dev
