---
resources:
  - name: dev
    type: git
    source:
      uri: https://github.com/demonintherough/talent-id
      branch: dev
  - name: master
    type: git
    source:
      uri: https://github.com/demonintherough/talent-id
      branch: master

jobs:
  - name: JUnit Tests
    plan:
      - get: dev
        trigger: true
      - task: run the Unit test suite
        file: dev/ci/tasks/Unit_tests.yml
  - name: CodeceptJS UI Tests
    plan:
      - get: dev
        trigger: true
      - task: run the UI test suite
        file: dev/ci/tasks/UI_tests.yml
  - name: push to master
    plan:
      - get: dev
        trigger: true
        passed: [JUnit Tests]
      - task: push to master
        file: dev/ci/tasks/push_to_master.yml
      - put: master
        params:
          repository: dev
