---
resources:
  - name: talent_id
    type: git
    source: &repo-source
      uri: https://github.com/demonintherough/talent-id
      branch: master

jobs:
  - name: Run tests
    plan:
      - get: talent_id
        trigger: true
      - task: run the test suite
        file: talent_id/ci/tasks/run_tests.yml
