---
resources:
  - name: talent_id
    type: git
    source: &repo-source
      uri: https://github.com/demonintherough/talent-id
      branch: master

jobs:
  - name: Jest Unit Tests
    plan:
      - get: talent_id
        trigger: true
      - task: run the Unit test suite
        file: talent_id/ci/tasks/Unit_tests.yml
  - name: CodeceptJS UI Tests
    plan:
      - get: talent_id
        triger: true
      - task: run the UI test suite
        file: talent_id/ci/tasks/UI_tests.yml